# Generated by Django 2.2.16 on 2020-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201008_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='value',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='price',
            field=models.CharField(blank=True, max_length=60, verbose_name='число'),
        ),
    ]
