# Generated by Django 2.2.16 on 2020-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201008_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='price',
            field=models.CharField(blank=True, max_length=60, verbose_name='краткое описание продукта'),
        ),
    ]
