# Generated by Django 2.2.16 on 2020-10-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201008_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='price',
        ),
    ]
