# Generated by Django 2.2.16 on 2020-10-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='summaly',
            field=models.PositiveIntegerField(default=0, verbose_name='сумма'),
        ),
    ]
