# Generated by Django 2.2.16 on 2020-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_basket_summaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='summaly',
        ),
    ]
